include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml


# 4
stages:
  - init
  - E2E_Testing
  - test
 

sast:
  variables:
    SAST_EXCLUDED_ANALYZERS: bandit, brakeman, eslint, flawfinder, gosec, kubesec,
      nodejs-scan, pmd-apex, security-code-scan, sobelow, spotbugs
  stage: test
  tags:
      - CI_SAST
  rules:
    # - if: $CI_COMMIT_BRANCH == "gitlab-ci-setup"
    - if: $CI_MERGE_REQUEST_ID

brakeman-sast:
   tags:
      - CI_SAST
eslint-sast:
    tags:
    - CI_SAST
flawfinder-sast:
   tags:
      - CI_SAST  
phpcs-security-audit-sast:
  tags:
      - CI_SAST
  rules:
    # - if: $CI_COMMIT_BRANCH == "gitlab-ci-setup"
    - if: $CI_MERGE_REQUEST_ID

security-code-scan-sast:
     tags:
      - CI_SAST
spotbugs-sast:
   tags:
      - CI_SAST
secret_detection:
   tags:
      - CI_SAST
   rules:
     # - if: $CI_COMMIT_BRANCH == "gitlab-ci-setup"
      - if: $CI_MERGE_REQUEST_ID


variables:
  BILLING_DB: 'billing'
  BILLING_DB_PORT: 27617  
  BRANCH_NAME: $CI_COMMIT_REF_NAME

# default:
      
.common_settings: 
    rules:
    # - if: $CI_COMMIT_BRANCH == "gitlab-ci-setup"
      - if: $CI_MERGE_REQUEST_ID
    tags:
      - CI_DEV    
    before_script:
      - export prefix=`pwd`
      - source $prefix/ci/scripts/gitlab-ci.sh


db_setup:
    extends: .common_settings 
    stage: init    
    script:
      - RESET_MONGO_DB $BILLING_DB $BILLING_DB_PORT 

testing:
    extends: .common_settings 
    stage: E2E_Testing
    script:      
      - RUN_TEST "http://46.101.14.10"    
