# 2
stages:
  - init
  - test

variables:
  BILLING_DB: 'billing'
  BILLING_DB_PORT: 27617  
  BRANCH_NAME: $CI_COMMIT_REF_NAME

default:
  before_script:
    - export prefix=`pwd`
    - source $prefix/ci/scripts/gitlab-ci.sh
      
common_settings: 
    only:
      - merge_requests

db_setup:
    extends: 
      - .common_settings 
    stage: init
    tags:
      - CI_DEV
    script:
      - RESET_MONGO_DB $BILLING_DB $BILLING_DB_PORT 

testing:
    extends: 
      - .common_settings 
    stage: test
    tags:
      - CI_DEV
    script:      
      - RUN_TEST "http://46.101.14.10"    

